name: Integração automática Xray

on:
  push:
    branches:
      - main

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Playwright
        run: node ./node_modules/playwright/cli.js install chromium

      - name: Executar testes
        run: npm test

      - name: Autenticar Xray
        id: auth
        run: |
          response=$(curl -H "Content-Type: application/json" \
          -X POST \
          --data "{\"client_id\":\"${{ secrets.XRAY_CLIENT_ID }}\",\"client_secret\":\"${{ secrets.XRAY_CLIENT_SECRET }}\"}" \
          https://xray.cloud.getxray.app/api/v2/authenticate)

          echo "token=$response" >> $GITHUB_OUTPUT

      - name: Enviar resultado para Xray
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
          --data @reports/cucumber-report.json \
          https://xray.cloud.getxray.app/api/v2/import/execution/cucumber
          