name: Integração automática Xray

on:
  push:
    branches:
      - principal
      - main

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Playwright
        run: npx playwright install chromium --with-deps

      - name: Executar testes
        run: npm test
        